### ISSUE TITLE
Open Invitation - how did you do it?

### ISSUE THREAD

**Issue by ckib16** [pushcx/lobsters#3]
Hey @pushcx & @jcs - thanks to you both for Lobste.rs & Barnacl.es.

@pushcx - I'm trying to figure out how you got around the "invite-only" mode of adding users to Lobste.rs (see pic below)

I think I pinned it down to this commit - 
   `Allow direct signup; 'git revert' when done` - https://github.com/pushcx/barnacl.es/commit/d26d02c3378ff9e00833bccef5f09ef23486a170

My questions:
- [x] Is this commit the only changes you remember making to create the "direct signup" function?
- [x] Was there something to the `'git revert' when done` portion of the commit comment that you can remember? Couldn't really follow that part. Wasn't sure if I was missing something.

Much appreciated!

![screen shot 2017-01-23 at 22 33 10](https://cloud.githubusercontent.com/assets/2160186/22233148/2bb7486c-e1bc-11e6-9532-637d3c7d098a.png)

**Comment by pushcx** [comment]
Yes, commit d26d02c3378ff9e00833bccef5f09ef23486a170 is the only one I made to make signups open. There may be an extra commit or two tweaking wording on the views, but that's all the code. The idea is that invitations have a unique code and build a URL like `/invitations/avnrmka`. I left that alone and used the code "open" (for the nice url `/invitations/open`) in my URLs so I didn't have to mess with routes or anything, it considers any invite code valid.

The "'git revert' when done" was a note to myself that this commit was the only commit changing invites. When (if) barnacl.es is done with open invites, I can revert that commit to turn the invite system back on.

Good luck with your site, please do tweet me a link when it's live. If you want to keep the silly naming scheme, [here's my old notes](https://lobste.rs/s/jtfpei/barnacles_lobsters_install_for_small/comments/bbqg3r#c_bbqg3r) of available domains. Finally, the [lobsters chat room](https://lobste.rs/chat) has me and a few other folks who know the Lobste.rs codebase decently.

**Comment by ckib16** [comment]
Fantastic. Thank you very much. I was stumbling around on this for hours but never thought of this approach.

One small thing that may help you - I noticed on your "About" page that the "Invitation Tree" section still has wording on being invite only (see below).

I'm sure not many people will read our about pages :)  ... but just wanted to mention it. I'm trying to clean up similar text myself.

Yeah definitely will let you know when it's finished - hoping in next week or two for MVP. It's focused on the "private label" eCommerce audience. It will look strikingly similar to yours and @jcs :) . This commit will speed me up! So far I have a weekly newsletter at https://private-label-weekly.ongoodbits.com/ that curates links. Hoping the app helps grow the audience in this niche like your app has.

Thanks again.

![screen shot 2017-01-24 at 08 10 26](https://cloud.githubusercontent.com/assets/2160186/22248739/0da60230-e20e-11e6-9df2-a07166b0e631.png)
